<?xml version="1.0" encoding="utf-8"?><Database Name="EntrenadorPersonal" Class="BDEntrenadorPersonalDataContextDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=MSI;Initial Catalog=EntrenadorPersonal;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="EntrenadorPersonalConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Entrenadores" Member="Entrenadores">
    <Type Name="Entrenadores">
      <Column Name="EntrenadorID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Apellido" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Especialidad" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Telefono" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="Usuario" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Contraseña" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="habilitado" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Entrenadores_Clientes" Member="Clientes" ThisKey="EntrenadorID" OtherKey="EntrenadorID" Type="Clientes" />
    </Type>
  </Table>
  <Table Name="dbo.Clientes" Member="Clientes">
    <Type Name="Clientes">
      <Column Name="ClienteID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Apellido" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Telefono" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="FechaInicio" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="EntrenadorID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Clientes_EvolucionClientes" Member="EvolucionClientes" ThisKey="ClienteID" OtherKey="ClienteID" Type="EvolucionClientes" />
      <Association Name="Entrenadores_Clientes" Member="Entrenadores" ThisKey="EntrenadorID" OtherKey="EntrenadorID" Type="Entrenadores" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.EvolucionClientes" Member="EvolucionClientes">
    <Type Name="EvolucionClientes">
      <Column Name="EvolucionID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ClienteID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Fecha" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Peso" Type="System.Decimal" DbType="Decimal(5,2)" CanBeNull="true" />
      <Column Name="GrasaCorporal" Type="System.Decimal" DbType="Decimal(5,2)" CanBeNull="true" />
      <Column Name="Musculo" Type="System.Decimal" DbType="Decimal(5,2)" CanBeNull="true" />
      <Column Name="Comentarios" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Association Name="Clientes_EvolucionClientes" Member="Clientes" ThisKey="ClienteID" OtherKey="ClienteID" Type="Clientes" IsForeignKey="true" />
    </Type>
  </Table>
</Database>